name: Tech Data Extractor

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday

jobs:
  tech-data-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Ensures the correct permissions to push the changes

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Tech Data Extractor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python tech_data_extractor.py

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Commit Changes
      run: |
        git add tech_data.json
        git commit -m "Update tech data JSON file"
        git push origin main  # Push the commit to the main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
